main: net.akihamitsuki.slash_command_clone.Main
name: slash_command_clone
version: 0.1
api-version: 1.18
commands:
  clear-:
  defaultgamemode-:
  effect-:
  enchant-:
  gamemode-:
  give-:
  kill-:
  particle-:
  playsound-:
  setblock-:
  stopsound-:
  summon-:
  teleport-:
    aliases: [tp-]
  time-:
  title-:
  weather-:
