main: net.akihamitsuki.slash_command_clone.Main
name: slash_command_clone
version: 0.1
api-version: 1.18
commands:
  bossbar-:
  clear-:
  defaultgamemode-:
  difficulty-:
  effect-:
  enchant-:
  experience-:
    aliases: [xp-]
  gamemode-:
  gamerule-:
  give-:
  kill-:
  particle-:
  playsound-:
  setblock-:
  setworldspawn-:
  spawnpoint-:
  stopsound-:
  summon-:
  teleport-:
    aliases: [tp-]
  time-:
  title-:
  weather-:
